-- Generated by scripts/dump_cockroach_schema.py
-- Schema: openfoodfacts
--
-- This file is a snapshot of the current CockroachDB DDL. Treat the CSV headers
-- as the primary source-of-truth for ingestion; USDA may add columns over time.


--
-- openfoodfacts.import_metadata
--
CREATE TABLE openfoodfacts.import_metadata (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	imported_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ,
	source_url STRING NULL,
	file_path STRING NULL,
	file_sha256 STRING NULL,
	file_bytes INT8 NULL,
	delimiter STRING NULL,
	nutrients_mode STRING NULL,
	CONSTRAINT import_metadata_pkey PRIMARY KEY (id ASC)
);

--
-- openfoodfacts.nutrient_100g
--
CREATE TABLE openfoodfacts.nutrient_100g (
	code_norm STRING NOT NULL,
	nutrient_key STRING NOT NULL,
	value FLOAT8 NULL,
	unit STRING NULL,
	source_field STRING NULL,
	CONSTRAINT nutrient_100g_pkey PRIMARY KEY (code_norm ASC, nutrient_key ASC)
);

--
-- openfoodfacts.product_raw
--
CREATE TABLE openfoodfacts.product_raw (
	code_norm STRING NOT NULL,
	code_raw STRING NULL,
	product_name STRING NULL,
	brands STRING NULL,
	categories STRING NULL,
	quantity STRING NULL,
	serving_size STRING NULL,
	last_modified_t INT8 NULL,
	energy_kcal_100g FLOAT8 NULL,
	energy_kj_100g FLOAT8 NULL,
	fat_100g FLOAT8 NULL,
	saturated_fat_100g FLOAT8 NULL,
	carbohydrates_100g FLOAT8 NULL,
	sugars_100g FLOAT8 NULL,
	fiber_100g FLOAT8 NULL,
	protein_100g FLOAT8 NULL,
	sodium_100g FLOAT8 NULL,
	salt_100g FLOAT8 NULL,
	CONSTRAINT product_raw_pkey PRIMARY KEY (code_norm ASC)
);
