-- Generated by scripts/dump_cockroach_schema.py
-- Schema: usda
--
-- This file is a snapshot of the current CockroachDB DDL. Treat the CSV headers
-- as the primary source-of-truth for ingestion; USDA may add columns over time.


--
-- usda.branded_food
--
CREATE TABLE usda.branded_food (
	fdc_id INT8 NOT NULL,
	brand_owner STRING NULL,
	brand_name STRING NULL,
	subbrand_name STRING NULL,
	gtin_upc STRING NULL,
	ingredients STRING NULL,
	not_a_significant_source_of STRING NULL,
	serving_size FLOAT8 NULL,
	serving_size_unit STRING NULL,
	household_serving_fulltext STRING NULL,
	branded_food_category STRING NULL,
	data_source STRING NULL,
	package_weight STRING NULL,
	modified_date DATE NULL,
	available_date DATE NULL,
	market_country STRING NULL,
	discontinued_date DATE NULL,
	preparation_state_code STRING NULL,
	trade_channel STRING NULL,
	short_description STRING NULL,
	material_code STRING NULL,
	CONSTRAINT branded_food_pkey PRIMARY KEY (fdc_id ASC)
);

--
-- usda.food
--
CREATE TABLE usda.food (
	fdc_id INT8 NULL,
	data_type STRING NULL,
	description STRING NULL,
	food_category_id STRING NULL,
	publication_date DATE NULL,
	rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
	CONSTRAINT food_pkey PRIMARY KEY (rowid ASC)
);

--
-- usda.food_category
--
CREATE TABLE usda.food_category (
	id INT8 NOT NULL,
	code STRING NULL,
	description STRING NULL,
	CONSTRAINT food_category_pkey PRIMARY KEY (id ASC)
);
