#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from pathlib import Path

import psycopg
from psycopg import sql


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Dump CREATE TABLE statements for a CockroachDB schema.",
    )
    parser.add_argument(
        "--schema",
        required=True,
        help="Schema name to dump (e.g. usda).",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output path for the SQL dump (e.g. docs/schema/usda_2025-12-18.sql).",
    )
    parser.add_argument(
        "--database-url-env",
        default="DATABASE_URL",
        help="Env var name containing the DB connection string (default: DATABASE_URL).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    db_url = os.environ.get(args.database_url_env)
    if not db_url:
        raise SystemExit(f"{args.database_url_env} is not set")

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with psycopg.connect(db_url, connect_timeout=10) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = %s
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """,
                (args.schema,),
            )
            tables = [row[0] for row in cur.fetchall()]

            pieces: list[str] = []
            pieces.append(
                "-- Generated by scripts/dump_cockroach_schema.py\n"
                f"-- Schema: {args.schema}\n"
                "--\n"
                "-- This file is a snapshot of the current CockroachDB DDL. Treat the CSV headers\n"
                "-- as the primary source-of-truth for ingestion; USDA may add columns over time.\n"
                "\n"
            )

            for table in tables:
                stmt = sql.SQL("SHOW CREATE TABLE {}.{}").format(
                    sql.Identifier(args.schema), sql.Identifier(table)
                )
                cur.execute(stmt)
                create_sql = cur.fetchone()[1]
                pieces.append(f"--\n-- {args.schema}.{table}\n--\n{create_sql}\n")

    output_path.write_text("\n".join(pieces), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
